2025-05-31 11:28:01,311 ERROR 采集或入库时出错: api init error.
Traceback (most recent call last):
  File "E:\wangxw\股票分析软件\编码\stock_quote_analayze\backend_core\data_collectors\tushare\realtime.py", line 56, in collect_quotes
    df = ts.pro_bar()  # 这里需要根据tushare实际API替换
         ^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\tushare\pro\data_pro.py", line 99, in pro_bar
    api = api if api is not None else pro_api()
                                      ^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\tushare\pro\data_pro.py", line 212, in pro_api
    raise Exception('api init error.')
Exception: api init error.
2025-05-31 11:28:01,313 ERROR 记录错误日志失败: cannot access local variable 'cursor' where it is not associated with a value
2025-05-31 11:34:07,601 INFO 采集到 6000 条股票行情数据
2025-05-31 11:34:08,272 INFO 全部股票行情数据采集并入库完成
2025-05-31 14:21:53,585 ERROR 采集或入库时出错: 您的token不对，请确认。
Traceback (most recent call last):
  File "E:\wangxw\股票分析软件\编码\stock_quote_analayze\backend_core\data_collectors\tushare\realtime.py", line 69, in collect_quotes
    stocks = pro.stock_basic(exchange='', list_status='L')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tushare\pro\client.py", line 45, in query
    raise Exception(result['msg'])
Exception: 您的token不对，请确认。
2025-05-31 14:21:53,587 ERROR 记录错误日志失败: cannot access local variable 'cursor' where it is not associated with a value
2025-05-31 14:21:58,119 ERROR 采集或入库时出错: 您的token不对，请确认。
Traceback (most recent call last):
  File "E:\wangxw\股票分析软件\编码\stock_quote_analayze\backend_core\data_collectors\tushare\realtime.py", line 69, in collect_quotes
    stocks = pro.stock_basic(exchange='', list_status='L')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tushare\pro\client.py", line 45, in query
    raise Exception(result['msg'])
Exception: 您的token不对，请确认。
2025-05-31 14:21:58,119 ERROR 记录错误日志失败: cannot access local variable 'cursor' where it is not associated with a value
2025-05-31 14:22:28,265 ERROR 采集或入库时出错: 您的token不对，请确认。
Traceback (most recent call last):
  File "E:\wangxw\股票分析软件\编码\stock_quote_analayze\backend_core\data_collectors\tushare\realtime.py", line 69, in collect_quotes
    stocks = pro.stock_basic(exchange='', list_status='L')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tushare\pro\client.py", line 45, in query
    raise Exception(result['msg'])
Exception: 您的token不对，请确认。
2025-05-31 14:22:28,266 ERROR 记录错误日志失败: cannot access local variable 'cursor' where it is not associated with a value
2025-05-31 14:26:10,178 INFO 获取到 5413 只股票
2025-05-31 14:26:10,233 ERROR 采集或入库时出错: HTTP Error 431: Request Header Fields Too Large
Traceback (most recent call last):
  File "E:\wangxw\股票分析软件\编码\stock_quote_analayze\backend_core\data_collectors\tushare\realtime.py", line 73, in collect_quotes
    df = ts.get_realtime_quotes(stocks['ts_code'].tolist())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tushare\stock\trading.py", line 382, in get_realtime_quotes
    text = urlopen(request,timeout=10).read()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 431: Request Header Fields Too Large
2025-05-31 14:26:10,233 ERROR 记录错误日志失败: cannot access local variable 'cursor' where it is not associated with a value
2025-05-31 14:49:09,323 ERROR 采集或入库时出错: 抱歉，您每小时最多访问该接口1次，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。
Traceback (most recent call last):
  File "E:\wangxw\股票分析软件\编码\stock_quote_analayze\backend_core\data_collectors\tushare\realtime.py", line 72, in collect_quotes
    stocks = pro.stock_basic(exchange='', list_status='L')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\tushare\pro\client.py", line 45, in query
    raise Exception(result['msg'])
Exception: 抱歉，您每小时最多访问该接口1次，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。
2025-05-31 14:49:09,324 ERROR 记录错误日志失败: cannot access local variable 'cursor' where it is not associated with a value
2025-05-31 16:46:01,480 ERROR 采集或入库时出错: HTTP Error 431: Request Header Fields Too Large
Traceback (most recent call last):
  File "E:\wangxw\股票分析软件\编码\stock_quote_analayze\backend_core\data_collectors\tushare\realtime.py", line 76, in collect_quotes
    df = ts.get_realtime_quotes(stocks['ts_code'].tolist())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\tushare\stock\trading.py", line 382, in get_realtime_quotes
    text = urlopen(request,timeout=10).read()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 431: Request Header Fields Too Large
2025-05-31 16:46:01,486 ERROR 记录错误日志失败: cannot access local variable 'cursor' where it is not associated with a value
